// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxkjyqdtgfghkihdmubw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14a2p5cWR0Z2ZnaGtpaGRtdWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTkxMjIsImV4cCI6MjA2NDI3NTEyMn0.8ktzwMa9JeJn05RElxbBeKublUS_eprDRvYAVPXNUw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);